const Interest = require("../models/interest.model");

const interestSeedData = [
  { name: "Reading" },
  { name: "Coding" },
  { name: "Hiking" },
  { name: "Traveling" },
  { name: "Cooking" },
  { name: "Baking" },
  { name: "Gardening" },
  { name: "Fishing" },
  { name: "Camping" },
  { name: "Photography" },
  { name: "Painting" },
  { name: "Drawing" },
  { name: "Singing" },
  { name: "Dancing" },
  { name: "Acting" },
  { name: "Knitting" },
  { name: "Sewing" },
  { name: "Woodworking" },
  { name: "Pottery" },
  { name: "Metalworking" },
  { name: "Leatherworking" },
  { name: "Cycling" },
  { name: "Running" },
  { name: "Swimming" },
  { name: "Fitness" },
  { name: "Yoga" },
  { name: "Meditation" },
  { name: "Bird Watching" },
  { name: "Collecting" },
  { name: "Board Games" },
  { name: "Video Games" },
  { name: "Puzzles" },
  { name: "Archery" },
  { name: "Surfing" },
  { name: "Skateboarding" },
  { name: "Snowboarding" },
  { name: "Skiing" },
  { name: "Rock Climbing" },
  { name: "Scuba Diving" },
  { name: "Paragliding" },
  { name: "Running" },
  { name: "Swimming" },
  { name: "Fitness" },
  { name: "Yoga" },
  { name: "Bird Watching" },
  { name: "Collecting" },
  { name: "Board Games" },
  { name: "Video Games" },
  { name: "Puzzles" },
  { name: "Archery" },
  { name: "Surfing" },
  { name: "Skateboarding" },
  { name: "Snowboarding" },
  { name: "Skiing" },
  { name: "Rock Climbing" },
  { name: "Scuba Diving" },
  { name: "Paragliding" },
  { name: "Astronomy" },
  { name: "Astrophotography" },
  { name: "Model Building" },
  { name: "Drones" },
  { name: "Geocaching" },
  { name: "Kayaking" },
  { name: "Stand-Up Paddleboarding" },
  { name: "Magic and Illusion" },
  { name: "Live Theater" },
  { name: "Museums" },
  { name: "Opera" },
  { name: "Symphony" },
  { name: "Ballet" },
  { name: "Craft Beer Brewing" },
  { name: "Wine Tasting" },
  { name: "Coffee Roasting" },
  { name: "Cheese Making" },
  { name: "Digital Art" },
  { name: "3D Printing" },
  { name: "Robotics" },
  { name: "Virtual Reality" },
  { name: "Esports" },
  { name: "Fantasy Sports" },
  { name: "Tabletop Role-Playing Games" },
  { name: "Cosplay" },
  { name: "Urban Exploration" },
  { name: "Volunteering" },
  { name: "Environmental Conservation" },
  { name: "Animal Rescue" },
  { name: "Historical Reenactment" },
  { name: "LARPing (Live Action Role-Playing)" },
  { name: "Genealogy" },
  { name: "Astronomy" },
  { name: "Astrophotography" },
  { name: "Model Building" },
  { name: "Drones" },
  { name: "Geocaching" },
  { name: "Kayaking" },
  { name: "Stand-Up Paddleboarding" },
  { name: "Magic and Illusion" },
  { name: "Live Theater" },
  { name: "Language Learning" },
  { name: "Calligraphy" },
  { name: "Journaling" },
  { name: "Podcasting" },
  { name: "Blogging" },
  { name: "Vlogging" },
  { name: "Social Media Influencing" },
  { name: "Home Brewing" },
  { name: "Mixology" },
  { name: "Sustainable Living" },
  { name: "Minimalism" },
  { name: "DIY Home Improvement" },
  { name: "Interior Design" },
  { name: "Event Planning" },
  { name: "Board Sports" },
  { name: "Martial Arts" },
  { name: "Archaeology" },
  { name: "Philosophy" },
  { name: "Chess" },
  { name: "Gourmet Cooking" },
  { name: "Food Styling" },
  { name: "Nutrition & Diet" },
  { name: "Personal Development" },
  { name: "Mindfulness" },
  { name: "Crypto & Blockchain" },
  { name: "Stock Market Investing" },
  { name: "Real Estate Investing" },
  { name: "Startup & Entrepreneurship" },
  { name: "Public Speaking" },
  { name: "Creative Writing" },
  { name: "Comic Book Art" },
  { name: "Graffiti Art" },
  { name: "Tattoo Art & Design" },
  { name: "Upcycling" },
  { name: "Gaming" },
  { name: "Console Gaming" },
  { name: "Mobile Gaming" },
  { name: "Retro Gaming" },
  { name: "Game Development" },
  { name: "Aquascaping" },
  { name: "Terrariums" },
  { name: "Bonsai" },
  { name: "Vegetable Gardening" },
  { name: "Herbalism" },
  { name: "Beekeeping" },
  { name: "Birdkeeping" },
  { name: "Aquarium Keeping" },
  { name: "Horseback Riding" },
  { name: "Motorsports" },
  { name: "Model Railroading" },
  { name: "Piloting" },
  { name: "Sailing" },
  { name: "Adventure Travel" },
  { name: "Backpacking" },
];
async function seedInterests() {
  try {
    const interests = await Interest.find();
    if (interests.length === 0) {
      console.log("No interests found, seeding...");
      await Interest.insertMany(
        // interestSeedData remove the duplicate interests
        interestSeedData.filter(
          (interest, index, self) =>
            index ===
            self.findIndex(
              (t) => t.name.toLowerCase() === interest.name.toLowerCase()
            )
        )
      );
      console.log("Interests have been successfully seeded.");
    } else {
      console.log("Interests already exist.");
    }
  } catch (error) {
    console.error("Error seeding interests:", error);
  }
}

module.exports = seedInterests;
