import { useTranslation } from "react-i18next";

export const useTranslatedAttributes = () => {
  const { t } = useTranslation();

  return {
    gender: [
      { name: t("attributes.gender.male"), _id: "male" },
      { name: t("attributes.gender.female"), _id: "female" },
      // { name: t("attributes.gender.other"), _id: "other" },
    ],
    maritalStatus: [
      { name: t("attributes.maritalStatus.single"), _id: "single" },
      { name: t("attributes.maritalStatus.married"), _id: "married" },
      { name: t("attributes.maritalStatus.divorced"), _id: "divorced" },
      { name: t("attributes.maritalStatus.widowed"), _id: "widowed" },
    ],
    lookingFor: [
      { name: t("attributes.lookingFor.friendship"), _id: "friendship" },
      { name: t("attributes.lookingFor.relationship"), _id: "relationship" },
      { name: t("attributes.lookingFor.chatting"), _id: "chatting" },
      { name: t("attributes.lookingFor.networking"), _id: "networking" },
      // { name: t("attributes.lookingFor.other"), _id: "other" },
    ],
    smoking: [
      { name: t("attributes.smoking.yes"), _id: "yes" },
      { name: t("attributes.smoking.no"), _id: "no" },
      { name: t("attributes.smoking.sometimes"), _id: "sometimes" },
      { name: t("attributes.smoking.tryingToQuit"), _id: "tryingToQuit" },
      { name: t("attributes.smoking.inSocialEvents"), _id: "inSocialEvents" },
    ],
    drinking: [
      { name: t("attributes.drinking.yes"), _id: "yes" },
      { name: t("attributes.drinking.no"), _id: "no" },
      { name: t("attributes.drinking.sometimes"), _id: "sometimes" },
      { name: t("attributes.drinking.tryingToQuit"), _id: "tryingToQuit" },
      { name: t("attributes.drinking.inSocialEvents"), _id: "inSocialEvents" },
    ],
    zodiacSign: [
      { name: t("attributes.zodiacSign.Aries"), _id: "Aries" },
      { name: t("attributes.zodiacSign.Taurus"), _id: "Taurus" },
      { name: t("attributes.zodiacSign.Gemini"), _id: "Gemini" },
      { name: t("attributes.zodiacSign.Cancer"), _id: "Cancer" },
      { name: t("attributes.zodiacSign.Leo"), _id: "Leo" },
      { name: t("attributes.zodiacSign.Virgo"), _id: "Virgo" },
      { name: t("attributes.zodiacSign.Libra"), _id: "Libra" },
      { name: t("attributes.zodiacSign.Scorpio"), _id: "Scorpio" },
      { name: t("attributes.zodiacSign.Sagittarius"), _id: "Sagittarius" },
      { name: t("attributes.zodiacSign.Capricorn"), _id: "Capricorn" },
      { name: t("attributes.zodiacSign.Aquarius"), _id: "Aquarius" },
      { name: t("attributes.zodiacSign.Pisces"), _id: "Pisces" },
    ],
    religion: [
      { name: t("attributes.religion.agnostic"), _id: "agnostic" },
      { name: t("attributes.religion.atheist"), _id: "atheist" },
      { name: t("attributes.religion.buddhist"), _id: "buddhist" },
      { name: t("attributes.religion.christian"), _id: "christian" },
      { name: t("attributes.religion.catholic"), _id: "catholic" },
      { name: t("attributes.religion.hindu"), _id: "hindu" },
      { name: t("attributes.religion.jewish"), _id: "jewish" },
      { name: t("attributes.religion.muslim"), _id: "muslim" },
      { name: t("attributes.religion.sikh"), _id: "sikh" },
      { name: t("attributes.religion.other"), _id: "other" },
    ],
    politicalViews: [
      { name: t("attributes.politicalViews.anarchist"), _id: "anarchist" },
      { name: t("attributes.politicalViews.centrist"), _id: "centrist" },
      { name: t("attributes.politicalViews.conservative"), _id: "conservative" },
      { name: t("attributes.politicalViews.liberal"), _id: "liberal" },
      { name: t("attributes.politicalViews.libertarian"), _id: "libertarian" },
      { name: t("attributes.politicalViews.moderate"), _id: "moderate" },
      { name: t("attributes.politicalViews.progressive"), _id: "progressive" },
      { name: t("attributes.politicalViews.socialist"), _id: "socialist" },
      { name: t("attributes.politicalViews.other"), _id: "other" },
    ],
    personalityType: [
      { name: "INTJ", _id: "INTJ" },
      { name: "ENTP", _id: "ENTP" },
      { name: "ISFJ", _id: "ISFJ" },
      { name: "ENFJ", _id: "ENFJ" },
      { name: "ISTP", _id: "ISTP" },
      { name: "ESFP", _id: "ESFP" },
      { name: "ESTJ", _id: "ESTJ" },
      { name: "INFJ", _id: "INFJ" },
      { name: "ISFP", _id: "ISFP" },
      { name: "ESTP", _id: "ESTP" },
      { name: "ENFP", _id: "ENFP" },
      { name: "INTP", _id: "INTP" },
      { name: "ENTJ", _id: "ENTJ" },
      { name: "ISTJ", _id: "ISTJ" },
      { name: "INFP", _id: "INFP" },
      { name: "ESFJ", _id: "ESFJ" },
    ],
    enum: [
      "no high school diploma",
      "high school diploma",
      "some college, no degree",
      "associate degree",
      "bachelor's degree",
      "master's degree",
      "doctorate or higher",
      "other",
      "",
    ],
    education: [
      {
        name: t("attributes.education.noHighSchoolDiploma"),
        _id: "no high school diploma",
      },
      {
        name: t("attributes.education.highSchoolDiploma"),
        _id: "high school diploma",
      },
      {
        name: t("attributes.education.someCollegeNoDegree"),
        _id: "some college, no degree",
      },
      { name: t("attributes.education.someCollege"), _id: "someCollege" },
      {
        name: t("attributes.education.associateDegree"),
        _id: "associate degree",
      },
      {
        name: t("attributes.education.bachelorsDegree"),
        _id: "bachelor's degree",
      },
      { name: t("attributes.education.mastersDegree"), _id: "master's degree" },
      {
        name: t("attributes.education.doctorateOrHigher"),
        _id: "doctorate or higher",
      },
      { name: t("attributes.education.other"), _id: "other" },
    ],
    preferredCommunications: [
      { name: t("attributes.preferredCommunications.text"), _id: "text" },
      { name: t("attributes.preferredCommunications.voice"), _id: "voice" },
      { name: t("attributes.preferredCommunications.video"), _id: "video" },
      {
        name: t("attributes.preferredCommunications.inPerson"),
        _id: "in person",
      },
    ],
    exercise: [
      { name: t("attributes.exercise.never"), _id: "never" },
      { name: t("attributes.exercise.rarely"), _id: "rarely" },
      { name: t("attributes.exercise.sometimes"), _id: "sometimes" },
      { name: t("attributes.exercise.daily"), _id: "daily" },
      { name: t("attributes.exercise.weekly"), _id: "weekly" },
      { name: t("attributes.exercise.monthly"), _id: "monthly" },
    ],

    diet: [
      { name: t("attributes.diet.anything"), _id: "anything" },
      { name: t("attributes.diet.vegetarian"), _id: "vegetarian" },
      { name: t("attributes.diet.vegan"), _id: "vegan" },
      { name: t("attributes.diet.pescatarian"), _id: "pescatarian" },
      { name: t("attributes.diet.keto"), _id: "keto" },
      { name: t("attributes.diet.paleo"), _id: "paleo" },
      { name: t("attributes.diet.glutenFree"), _id: "gluten-free" },
      { name: t("attributes.diet.halal"), _id: "halal" },
      { name: t("attributes.diet.kosher"), _id: "kosher" },
      { name: t("attributes.diet.other"), _id: "other" },
    ],
    sleepSchedule: [
      { name: t("attributes.sleepSchedule.earlyBird"), _id: "early bird" },
      { name: t("attributes.sleepSchedule.nightOwl"), _id: "night owl" },
      { name: t("attributes.sleepSchedule.varies"), _id: "varies" },
    ],

    bodyType: [
      { name: t("attributes.bodyType.slim"), _id: "slim" },
      { name: t("attributes.bodyType.average"), _id: "average" },
      { name: t("attributes.bodyType.athletic"), _id: "athletic" },
      { name: t("attributes.bodyType.fullFigured"), _id: "full-figured" },
      { name: t("attributes.bodyType.curvy"), _id: "curvy" },
      { name: t("attributes.bodyType.muscular"), _id: "muscular" },
      { name: t("attributes.bodyType.petite"), _id: "petite" },
      { name: t("attributes.bodyType.aLittleExtra"), _id: "a little extra" },
      { name: t("attributes.bodyType.stocky"), _id: "stocky" },
      { name: t("attributes.bodyType.other"), _id: "other" },
    ],
    themes: [
      { name: t("general.dark"), _id: "dark" },
      { name: t("general.light"), _id: "light" },
    ],

    years: [
      { label: "1900", value: 1900, _id: 1900 },
      { label: "1901", value: 1901, _id: 1901 },
      { label: "1902", value: 1902, _id: 1902 },
      { label: "1903", value: 1903, _id: 1903 },
      { label: "1904", value: 1904, _id: 1904 },
      { label: "1905", value: 1905, _id: 1905 },
      { label: "1906", value: 1906, _id: 1906 },
      { label: "1907", value: 1907, _id: 1907 },
      { label: "1908", value: 1908, _id: 1908 },
      { label: "1909", value: 1909, _id: 1909 },
      { label: "1910", value: 1910, _id: 1910 },
      { label: "1911", value: 1911, _id: 1911 },
      { label: "1912", value: 1912, _id: 1912 },
      { label: "1913", value: 1913, _id: 1913 },
      { label: "1914", value: 1914, _id: 1914 },
      { label: "1915", value: 1915, _id: 1915 },
      { label: "1916", value: 1916, _id: 1916 },
      { label: "1917", value: 1917, _id: 1917 },
      { label: "1918", value: 1918, _id: 1918 },
      { label: "1919", value: 1919, _id: 1919 },
      { label: "1920", value: 1920, _id: 1920 },
      { label: "1921", value: 1921, _id: 1921 },
      { label: "1922", value: 1922, _id: 1922 },
      { label: "1923", value: 1923, _id: 1923 },
      { label: "1924", value: 1924, _id: 1924 },
      { label: "1925", value: 1925, _id: 1925 },
      { label: "1926", value: 1926, _id: 1926 },
      { label: "1927", value: 1927, _id: 1927 },
      { label: "1928", value: 1928, _id: 1928 },
      { label: "1929", value: 1929, _id: 1929 },
      { label: "1930", value: 1930, _id: 1930 },
      { label: "1931", value: 1931, _id: 1931 },
      { label: "1932", value: 1932, _id: 1932 },
      { label: "1933", value: 1933, _id: 1933 },
      { label: "1934", value: 1934, _id: 1934 },
      { label: "1935", value: 1935, _id: 1935 },
      { label: "1936", value: 1936, _id: 1936 },
      { label: "1937", value: 1937, _id: 1937 },
      { label: "1938", value: 1938, _id: 1938 },
      { label: "1939", value: 1939, _id: 1939 },
      { label: "1940", value: 1940, _id: 1940 },
      { label: "1941", value: 1941, _id: 1941 },
      { label: "1942", value: 1942, _id: 1942 },
      { label: "1943", value: 1943, _id: 1943 },
      { label: "1944", value: 1944, _id: 1944 },
      { label: "1945", value: 1945, _id: 1945 },
      { label: "1946", value: 1946, _id: 1946 },
      { label: "1947", value: 1947, _id: 1947 },
      { label: "1948", value: 1948, _id: 1948 },
      { label: "1949", value: 1949, _id: 1949 },
      { label: "1950", value: 1950, _id: 1950 },
      { label: "1951", value: 1951, _id: 1951 },
      { label: "1952", value: 1952, _id: 1952 },
      { label: "1953", value: 1953, _id: 1953 },
      { label: "1954", value: 1954, _id: 1954 },
      { label: "1955", value: 1955, _id: 1955 },
      { label: "1956", value: 1956, _id: 1956 },
      { label: "1957", value: 1957, _id: 1957 },
      { label: "1958", value: 1958, _id: 1958 },
      { label: "1959", value: 1959, _id: 1959 },
      { label: "1960", value: 1960, _id: 1960 },
      { label: "1961", value: 1961, _id: 1961 },
      { label: "1962", value: 1962, _id: 1962 },
      { label: "1963", value: 1963, _id: 1963 },
      { label: "1964", value: 1964, _id: 1964 },
      { label: "1965", value: 1965, _id: 1965 },
      { label: "1966", value: 1966, _id: 1966 },
      { label: "1967", value: 1967, _id: 1967 },
      { label: "1968", value: 1968, _id: 1968 },
      { label: "1969", value: 1969, _id: 1969 },
      { label: "1970", value: 1970, _id: 1970 },
      { label: "1971", value: 1971, _id: 1971 },
      { label: "1972", value: 1972, _id: 1972 },
      { label: "1973", value: 1973, _id: 1973 },
      { label: "1974", value: 1974, _id: 1974 },
      { label: "1975", value: 1975, _id: 1975 },
      { label: "1976", value: 1976, _id: 1976 },
      { label: "1977", value: 1977, _id: 1977 },
      { label: "1978", value: 1978, _id: 1978 },
      { label: "1979", value: 1979, _id: 1979 },
      { label: "1980", value: 1980, _id: 1980 },
      { label: "1981", value: 1981, _id: 1981 },
      { label: "1982", value: 1982, _id: 1982 },
      { label: "1983", value: 1983, _id: 1983 },
      { label: "1984", value: 1984, _id: 1984 },
      { label: "1985", value: 1985, _id: 1985 },
      { label: "1986", value: 1986, _id: 1986 },
      { label: "1987", value: 1987, _id: 1987 },
      { label: "1988", value: 1988, _id: 1988 },
      { label: "1989", value: 1989, _id: 1989 },
      { label: "1990", value: 1990, _id: 1990 },
      { label: "1991", value: 1991, _id: 1991 },
      { label: "1992", value: 1992, _id: 1992 },
      { label: "1993", value: 1993, _id: 1993 },
      { label: "1994", value: 1994, _id: 1994 },
      { label: "1995", value: 1995, _id: 1995 },
      { label: "1996", value: 1996, _id: 1996 },
      { label: "1997", value: 1997, _id: 1997 },
      { label: "1998", value: 1998, _id: 1998 },
      { label: "1999", value: 1999, _id: 1999 },
      { label: "2000", value: 2000, _id: 2000 },
      { label: "2001", value: 2001, _id: 2001 },
      { label: "2002", value: 2002, _id: 2002 },
      { label: "2003", value: 2003, _id: 2003 },
      { label: "2004", value: 2004, _id: 2004 },
      { label: "2005", value: 2005, _id: 2005 },
      { label: "2006", value: 2006, _id: 2006 },
      { label: "2007", value: 2007, _id: 2007 },
    ],
    months: [
      { label: "January", value: 1, _id: 1 },
      { label: "February", value: 2, _id: 2 },
      { label: "March", value: 3, _id: 3 },
      { label: "April", value: 4, _id: 4 },
      { label: "May", value: 5, _id: 5 },
      { label: "June", value: 6, _id: 6 },
      { label: "July", value: 7, _id: 7 },
      { label: "August", value: 8, _id: 8 },
      { label: "September", value: 9, _id: 9 },
      { label: "October", value: 10, _id: 10 },
      { label: "November", value: 11, _id: 11 },
      { label: "December", value: 12, _id: 12 },
    ],

    days: [
      { label: "1", value: 1, _id: 1 },
      { label: "2", value: 2, _id: 2 },
      { label: "3", value: 3, _id: 3 },
      { label: "4", value: 4, _id: 4 },
      { label: "5", value: 5, _id: 5 },
      { label: "6", value: 6, _id: 6 },
      { label: "7", value: 7, _id: 7 },
      { label: "8", value: 8, _id: 8 },
      { label: "9", value: 9, _id: 9 },
      { label: "10", value: 10, _id: 10 },
      { label: "11", value: 11, _id: 11 },
      { label: "12", value: 12, _id: 12 },
      { label: "13", value: 13, _id: 13 },
      { label: "14", value: 14, _id: 14 },
      { label: "15", value: 15, _id: 15 },
      { label: "16", value: 16, _id: 16 },
      { label: "17", value: 17, _id: 17 },
      { label: "18", value: 18, _id: 18 },
      { label: "19", value: 19, _id: 19 },
      { label: "20", value: 20, _id: 20 },
      { label: "21", value: 21, _id: 21 },
      { label: "22", value: 22, _id: 22 },
      { label: "23", value: 23, _id: 23 },
      { label: "24", value: 24, _id: 24 },
      { label: "25", value: 25, _id: 25 },
      { label: "26", value: 26, _id: 26 },
      { label: "27", value: 27, _id: 27 },
      { label: "28", value: 28, _id: 28 },
      { label: "29", value: 29, _id: 29 },
      { label: "30", value: 30, _id: 30 },
      { label: "31", value: 31, _id: 31 },
    ],
  };
};

export const PAGE_SIZE = 25;
